realm/realm-cpp

- README.md
- Using designated initializers (`{.name = "Rex"...}`) requires aggregate class, in this case all public members (public inheritance). Switch to struct to avoid redundant public keywords
- Fix typos
> Update code examples in README

- src/CMakeLists.txt
This line of code was accidentally removed in the last PR. It prevented the shared library from being installed on the users system.
> Address issue where libcpprealm was not being installed

- .github/workflows/publish-doxygen.yml
- Doxyfile
...so we know which commit built the docs
> Add prealpha version info to doxygen

- .github/workflows/publish-doxygen.yml
Change the version label at the top of the autogenerated Doxygen API docs from "Pre-alpha" to "Alpha"
> Update the version label in the doxygen docs to Alpha

- src/cpprealm/internal/curl/network_transport.cpp
the response code is using int, which is not right according to https://curl.se/libcurl/c/CURLINFO_RESPONSE_CODE.html
> fix network_transport.cpp bug

- CHANGELOG.md
- src/cpprealm/app.cpp
- src/cpprealm/app.hpp
- src/cpprealm/internal/apple/network_transport.mm
- src/cpprealm/internal/bridge/realm.cpp
- src/cpprealm/internal/bridge/realm.hpp
- src/cpprealm/internal/curl/network_transport.cpp
- src/cpprealm/internal/generic_network_transport.hpp
- src/cpprealm/internal/network/network_transport.cpp
Adds ability to set custom http headers. Usage:
```cpp
auto headers = std::map<std::string, std::string>({{"Proxy-Authorization", "some-type some-credentials"}});
auto app = realm::App(Admin::shared().cached_app_id(), std::nullopt, std::nullopt, headers);
auto user = app.login(realm::App::credentials::anonymous()).get();
auto flx_sync_config = user.flexible_sync_configuration();
flx_sync_config.set_custom_http_headers(headers);
```
> Add ability to set custom http headers

- CHANGELOG.md
- src/cpprealm/app.cpp
- src/cpprealm/app.hpp
- src/cpprealm/internal/bridge/realm.cpp
- src/cpprealm/internal/bridge/realm.hpp
- tests/alpha/app_tests.cpp
- tests/alpha/asymmetric_object_tests.cpp
- tests/alpha/flx_sync_tests.cpp
- tests/experimental/db/realm_tests.cpp
- tests/experimental/sync/app_tests.cpp
- tests/experimental/sync/asymmetric_object_tests.cpp
- tests/experimental/sync/flexible_sync_tests.cpp
* The Sync metadata Realm is now encrypted by default on Apple platforms unless the `REALM_DISABLE_METADATA_ENCRYPTION` environment variable is set.
To enable encryption on the metadata Realm on other platforms you must set an encryption key on `realm::App::configuration`.
```cpp
std::array<char, 64> example_key = {...};
realm::App::configuration app_config;
app_config.app_id = ...
app_config.metadata_encryption_key = example_key;
auto encrypted_app = realm::App(app_config);
```
* Add ability to encrypt a Realm. Usage: `realm::config::set_encryption_key(const std::array<char, 64>&)`.
* `realm::App(const std::string &app_id, const std::optional<std::string> &base_url,
const std::optional<std::string> &path, const std::optional<std::map<std::string, std::string>> &custom_http_headers)` has …
> Add encryption support

- CHANGELOG.md
- src/CMakeLists.txt
- src/cpprealm/experimental/accessors.hpp
- src/cpprealm/experimental/db.hpp
- src/cpprealm/experimental/link.hpp
- src/cpprealm/experimental/macros.hpp
- src/cpprealm/experimental/managed_dictionary.hpp
- src/cpprealm/experimental/managed_list.hpp
- src/cpprealm/experimental/managed_set.hpp
- src/cpprealm/experimental/sdk.hpp
- src/cpprealm/experimental/types.hpp
- src/cpprealm/internal/bridge/generator/CMakeLists.txt
- src/cpprealm/internal/bridge/obj.hpp
- src/cpprealm/internal/bridge/object_schema.cpp
- src/cpprealm/internal/bridge/set.cpp
- src/cpprealm/internal/bridge/set.hpp
- src/cpprealm/internal/type_info.hpp
- src/cpprealm/notifications.hpp
- src/cpprealm/persisted_object_id.hpp
- src/cpprealm/persisted_uuid.hpp
- src/cpprealm/schema.hpp
- tests/CMakeLists.txt
- tests/experimental/db/list_tests.cpp
- tests/experimental/db/object_tests.cpp
- tests/experimental/db/set_tests.cpp
- tests/experimental/db/test_objects.hpp
- tests/experimental/sync/flexible_sync_tests.cpp
- tests/experimental/sync/test_objects.hpp
Adds support for `std::set` in object models.
```cpp
struct SetTypesObject {
primary_key<int64_t> _id;
std::set<int64_t> set_int_col;
std::set<double> set_double_col;
std::set<bool> set_bool_col;
std::set<std::string> set_str_col;
std::set<realm::uuid> set_uuid_col;
std::set<realm::object_id> set_object_id_col;
std::set<std::vector<std::uint8_t>> set_binary_col;
std::set<std::chrono::time_point<std::chrono::system_clock>> set_date_col;
std::set<realm::mixed> set_mixed_col;
std::set<AllTypesObjectLink*> set_obj_col;
};
REALM_SCHEMA(AllTypesObject,
_id, set_int_col, set_double_col, set_bool_col, set_str_col, set_uuid_col, set_object_id_col, set_binary_col,
set_date_col, set_mixed_col, set_obj_coll)
```
> Add std::set support

- .github/actions/publish-doxygen/action.yml
The Doxygen API reference pipeline has been failing due to a [missing shell error](https://github.com/realm/realm-cpp/actions/runs/6577926595/job/17870601142). Adding the shell here to resolve that failure.
> Fix missing shell in Doxygen publishing pipeline

- .github/actions/publish-doxygen/action.yml
- docs/fix-doxygen-titles.sh
Modify the Doxygen title fixup script to bypass permissions issues writing to `docs/html` directory. This should fix the Doxygen API reference docs publishing pipeline.
> Fix Doxygen publishing pipeline

- .idea/.name
- CHANGELOG.md
- src/cpprealm/experimental/db.cpp
- src/cpprealm/experimental/db.hpp
- src/cpprealm/experimental/macros.hpp
- src/cpprealm/experimental/managed_list.hpp
- src/cpprealm/experimental/results.hpp
- src/cpprealm/internal/bridge/list.cpp
- src/cpprealm/internal/bridge/list.hpp
- src/cpprealm/internal/bridge/obj.hpp
- src/cpprealm/internal/bridge/query.cpp
- src/cpprealm/internal/bridge/query.hpp
- src/cpprealm/internal/bridge/realm.cpp
- src/cpprealm/internal/bridge/realm.hpp
- src/cpprealm/internal/bridge/results.cpp
- src/cpprealm/internal/bridge/results.hpp
- tests/CMakeLists.txt
- tests/experimental/db/binary_tests.cpp
- tests/experimental/db/date_tests.cpp
- tests/experimental/db/decimal_tests.cpp
- tests/experimental/db/embedded_object_tests.cpp
- tests/experimental/db/frozen_tests.cpp
- tests/experimental/db/list_tests.cpp
- tests/experimental/db/object_id_tests.cpp
- tests/experimental/db/object_tests.cpp
- tests/experimental/db/query_tests.cpp
- tests/experimental/db/realm_tests.cpp
- tests/experimental/db/results_tests.cpp
- tests/experimental/sync/asymmetric_object_tests.cpp
- tests/experimental/sync/flexible_sync_tests.cpp
- Add support for Frozen Objects / Realm's
Usage: 
```cpp
auto realm = db(std::move(config));
realm.write([&realm]() {
realm.add(AllTypesObject());
});
auto frozen_realm = realm.freeze();
MY_ASSERT(frozen_realm.is_frozen();
auto async = std::async(std::launch::async, [&frozen_realm]() {
auto thawed = frozen_realm.thaw();
MY_ASSERT_FALSE(thawed.is_frozen());
thawed.write([&thawed]() {
auto o = AllTypesObject();
o._id = 2;
thawed.add(std::move(o));
});
thawed.write([&thawed]() {
auto o = AllTypesObject();
o._id = 3;
thawed.add(std::move(o));
});
MY_ASSERT_FALSE(thawed.refresh());
MY_ASSERT(thawed.objects<AllTypesObject>().size() == 3);
MY_ASSERT(frozen_realm.is_frozen());
MY_ASSERT_FALSE(frozen_realm.refresh());
MY_ASSERT(frozen_realm.objects<AllTypesObject>().size() == 1);
return true;
}); …
```
> Add support for Frozen Objects / Realm's

- CHANGELOG.md
- src/cpprealm/internal/bridge/sync_session.cpp
- src/cpprealm/internal/bridge/sync_session.hpp
- tests/experimental/sync/flexible_sync_tests.cpp
* Add the following methods for control over the sync session state:
- `realm::sync_session::pause()`
- `realm::sync_session::resume()`
- `realm::sync_session::reconnect()`
- `realm::sync_session::state()`
- `realm::sync_session::connection_state()`
- `realm::sync_session::observe_connection_change(std::function<void(enum connection_state old_state, 
enum connection_state new_state)>&& callback)`
- `realm::sync_session::unregister_connection_change_observer(uint64_t token)`
> Add sync control methods

- CHANGELOG.md
- src/cpprealm/internal/bridge/realm.cpp
- src/cpprealm/internal/bridge/realm.hpp
- tests/experimental/db/realm_tests.cpp
* Add support for manual compaction via `realm::db_config::should_compact_on_launch(std::function<bool(uint64_t total_bytes, uint64_t unused_bytes)>&&)`
> Add support for manual compaction

- CHANGELOG.md
- src/cpprealm/db.hpp
- src/cpprealm/macros.hpp
- src/cpprealm/notifications.hpp
- src/cpprealm/results.hpp
- src/cpprealm/thread_safe_reference.hpp
- tests/db/results_tests.cpp
When observing `results<>` the notifications would not fire after the `results<>` instance left the scope as the reference to the `internal::bridge::results` instance would call the destructor and tear down the collection notifier. To fix this the same pattern that we use with the other collection types must be followed when creating the notification token.
> Fix notifications when using results

- CHANGELOG.md
- Package.swift
- conanfile.py
- include/cpprealm/bson.hpp
- src/CMakeLists.txt
- src/cpprealm/app.cpp
- src/cpprealm/app.hpp
- src/cpprealm/bson.cpp
- src/cpprealm/bson.hpp
- src/cpprealm/internal/bridge/generator/CMakeLists.txt
- src/cpprealm/sdk.hpp
- tests/CMakeLists.txt
- tests/db/bson_tests.cpp
- tests/sync/app_tests.cpp
- tests/sync/asymmetric_object_tests.cpp
- tests/sync/client_reset_tests.cpp
- tests/sync/test_objects.hpp
This PR adds back BSON functionality by bridging the BSON classes found in RealmCore.
usage:
```cpp
auto bson = realm::bsoncxx();
bson = realm::bsoncxx((int32_t) 123);
bson = realm::bsoncxx((int64_t) 123);
bson = realm::bsoncxx(true);
bson = realm::bsoncxx(123.456);
bson = realm::bsoncxx(std::string("foo"));
bson = realm::bsoncxx(std::vector<uint8_t>({0, 0, 0, 0}));
bson = realm::bsoncxx(realm::bsoncxx::timestamp(100, 0));
auto d = std::chrono::system_clock::now();
bson = realm::bsoncxx(realm::bsoncxx::date(d));
auto oid = realm::object_id::generate();
bson = realm::bsoncxx(oid);
bson = realm::bsoncxx(realm::decimal128(123.456));
bson = realm::bsoncxx(realm::bsoncxx::regular_expression("[0-9]", "i"));
bson = realm::bsoncxx(realm::bsoncxx::max_key());
bson = …
```
> RCPP-61 Add BSON support

- CHANGELOG.md
- Package.swift
- include/cpprealm/app.hpp
- src/cpprealm/app.cpp
- tests/sync/app_tests.cpp
* Updated default base URL to be `https://services.cloud.mongodb.com` to support the new domains (was `https://realm.mongodb.com`)
> RCPP-55 Update to new base url

- Doxyfile
The `.hpp` files were recently moved to a new `/include` directory, which is outside the path that the Doxyfile uses to generate the API reference docs. This update to the Doxyfile should add all the classes back to the API reference.
> (DOCSP-38826): Add `include` path to Doxyfile for generating API reference docs

- .github/workflows/cmake.yml
- conanfile.py
- tests/admin_utils.cpp
- tests/admin_utils.hpp
- tests/sync/client_reset_tests.cpp
- tests/sync/test_objects.hpp
Fix flakey client reset tests, now uses the baas API to trigger a client reset.
The cmake.yml has been updated to not have duplicated jobs for sync and non sync tests.
> RCPP-11 Fix client reset tests

- .github/workflows/cmake.yml
- CHANGELOG.md
- conanfile.py
- src/CMakeLists.txt
Currently when building with CMake we default to always generating the bridging headers size and aligned size for usage in `std::aligned_storage`. This PR allows you to override that and use `std::shared_ptr`for the Core bridged types instead. This is required when we can't generate the bridging headers correctly or a package manager might not allow it.
> Add ability to disable aligned storage for bridged types

- .github/workflows/cmake.yml
- CHANGELOG.md
- include/cpprealm/internal/bridge/query.hpp
- include/cpprealm/managed_dictionary.hpp
- include/cpprealm/rbool.hpp
- src/cpprealm/internal/bridge/query.cpp
- tests/db/query_tests.cpp
Fixes https://github.com/realm/realm-cpp/issues/224
Add ability to use `managed<std::map<std::string, T>>` in type safe queries when comparing a value for a key. e.g.
`realm.object<MyObject>().where([](auto& o) { return o.my_map["foo_key"] == "some value"; })`
Supported operators are `==`, `!=`, `>`, `<`, `>=`, `<=` and `contains(const std::string&)`.
> RCPP-82 Add missing query operators for managed<std::map<std::string, T>>

- CHANGELOG.md
- include/cpprealm/internal/bridge/query.hpp
- include/cpprealm/managed_dictionary.hpp
- include/cpprealm/rbool.hpp
- src/cpprealm/internal/bridge/query.cpp
- tests/db/map_tests.cpp
- tests/db/query_tests.cpp
Add `managed<std::map<std::string, T>>::contains_key` for conveniently checking if a managed map contains a given key. Use this method in the Type Safe Query API instead of `managed<std::map<std::string, T>>::find`.
> Add contains_key to managed maps

- CHANGELOG.md
- include/cpprealm/internal/bridge/realm.hpp
- include/cpprealm/networking/websocket.hpp
- src/cpprealm/internal/bridge/realm.cpp
- src/cpprealm/networking/websocket.cpp
- tests/sync/flexible_sync_tests.cpp
Add ability to open a synced realm without a flexible sync configuration.
```cpp
auto local_config = realm::db_config();
local_config.set_path(path);
local_config.enable_forced_sync_history(); // allows a synced realm to be used with a local config.
```
> Add ability to open a synced realm without sync configuration.
